# Generated by Django 2.1.7 on 2019-03-18 12:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 18, 12, 25, 20, 590574, tzinfo=utc)),
        ),
    ]
