# Generated by Django 2.1.7 on 2019-03-18 16:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_auto_20190318_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 18, 16, 32, 14, 88356, tzinfo=utc)),
        ),
    ]
