# Generated by Django 2.2.3 on 2019-07-02 12:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0009_auto_20190320_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete='None', to=settings.AUTH_USER_MODEL),
        ),
    ]
